name: "Hello Actions"
description: "Greet something Special"
author: "sandeepmaxpayne@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Lovely World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
